### ISSUE TITLE
Bug: Fonts do not work with `useCssVariables`.

### ISSUE THREAD

**Issue by Rodielm** [jmjuanes/siimple#191]
### Describe the issue

It seems that using `useCssVariables` fonts do not work. 

### To reproduce

Add Roboto, Montserrat fonts to the `index.html `

```html
<html lang="en" data-color-mode="dark">
<head>
  <meta charset="UTF-8" />
  <link rel="icon" type="image/svg+xml" href="/vite.svg" />
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link
    href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600;800&family=Roboto:wght@400;500;800&display=swap"
    rel="stylesheet">
    <link rel="stylesheet" href="/siimple-beta.css">
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Vite + React</title>
</head>
<body>...</body
</html>

```

Use this config
```js
import ice from '@siimple/preset-ice'
import dark from '@siimple/preset-dark'

export default {
  useColorModes: true,
  useCssVariables: true,
  useColorModesMediaQuery: false,
  useRootStyles: true,
  useBorderBox: true,
  prefix: '',
  ...ice,
  colors: {
    ...ice.colors,
  },
  colorModes: {
    dark: { ...dark.colors },
  },
  fonts: {
    body: ['Roboto', 'sans-serif'],
    heading: ['Montserrat', 'sans-serif'],
    code: ['monospace'],
  },
}

```
Run this command: `npx siimple -c ./siimple.config.js -o ./siimple.css`

### What browser(s) are you seeing the problem on?

Chrome

### What version of **siimple** are you using?

4.3.0

**Comment by jmjuanes** [comment]
Hi @Rodielm. This seems that is a typo in the configuration example, fonts should be specified as a single string and not as an array. This should work:

```js
export default {
    fonts: {
        body: "'Roboto',sans-serif",
        heading: "'Montserrat',sans-serif",
        code: "monospace",
    },
    // ...other configuration
};
```

You can try it on this [playground](https://siimple.xyz/playground#html=DwEwlgbgfAEgpgGwQewAQHdkCcEmAenGgCgg&config=KYDwDg9gTgLgBAE2AMwIYFcA28DeAoOQuAWwgS2AGcAuOAbQF0AaAo9S4AJQghgGUYAT0xVaMKOmAsicdsADClSgDVUUAJaoARiJpxxk6UWQQAdjD34ZMrWUG0ARAHJutmBCdNKqU5QC0HBrIDkbWcAAWwKgI6qYA5o5OALJmFsBQUKgwnt6%2BAenqwaHWAMZkwI6kphCUYKglwCGshAC%2BxVA8MLRWYXAm5gBiqMTqmPZwDrYIgk0ybXgtANx4QA%3D).
