### ISSUE TITLE
Unable to display site in Dark mode on Safari Version 17.0 

### ISSUE THREAD

**Issue by martindufort** [jmjuanes/siimple#203]
### Describe the issue

Trying to enable dark mode for a simple web site using the following configuration. 

Site is always displayed black on white background. 
What am I missing?

### To reproduce

This is my siimple configuration:
```js
export default {
    useRootStyles: true,
    useBorderBox: true,
    useColorModes: true,
    useColorModesMediaQuery: true,
    useCssVariables: true,
    prefix: "",
    ...base,
    colors: {
        ...base.colors,
        primary: colors.blue["500"],
        secondary: colors.mint["600"],
        text: colors.gray["800"],
        background: "#fff",
        muted: colors.gray["200"],
    },
    colorModes: {
        dark: {
            text: "#fff",
            background: colors.gray["800"],
        },
    },
...
```

### What browser(s) are you seeing the problem on?

Safari

### What version of **siimple** are you using?

17.0

**Comment by jmjuanes** [comment]
Hello @martindufort. I have tried your configuration in the playground tool using Safari, and after enabling the dark mode in Mac it displays the dark background and white text 😕 

![image](https://github.com/jmjuanes/siimple/assets/5751201/ec0ffcba-080d-4740-9807-3b06617de58d)

Please could you check if the dark mode is enabled in your computer?

**Comment by martindufort** [comment]
This happened when the dark mode is auto-switched by macOS going from day to night. Load / Reloading the page still keeps light mode.

**Comment by jmjuanes** [comment]
I was still unable to reproduce the issue myself. I have tried this playground with auto-switch enabled in macOs and it uses the dark mode (in Spain it's 8PM)...

Please could you check it the issue happens with [this playground](https://siimple.xyz/playground#html=DwEwlgbgBAxgNgQwM5ILwCIxILQDM4CmAHlABbLbgBOBMALmAPYB22MjcArgLbNkVg6BbjhgFmQqvxwArTkga4Anm3GTp2AO55OcOBtLYAnADZ0APgBQUG1FCRYiFBnI5tAZgBMB7F40AjAHNKBCoAaygsbAAHMD0La1sk%2B2h4ZDR0DW1cXX1XbEMcvUicfGINQWFRNQIpfLkFMGVVCVqEpI7bYDBHdIwkMGwBsG5owg0BgC8CbAAODSEiOi1SSotgAHowK06bTfAIHa6Ng6O9g97ndHzuZZMJsGnfLON7%2FLG5jWiqT%2FzF5bErSo7V2ABVSAQ7P5zNwwMwRgg4JtoVAEMwQFDzHQIdwCAh%2FIRkeYoABhADKZKgdEYHDCggAdIk9idIGc7Bc0lcbstvFEkMJBFQ0UhoqE1CDOpopfThqNCPSiEpJky7CzDpZ9qzLEA%3D%3D%3D&config=PTAEE0HsFdQYwIYDtQEsC2AHSAnALqDDvJADa6iYKkCmeeNoek8ONCDoAnkUwBY10NAFAZs%2BEuRwBnUADMckdKABEAAWmoxtYHDK5pKgNzDhICDHjI0WXAUxtpdWc1A0AHgyQATUJu2M0JpIAOagbEEIAEa0fnhctLLIvngCQtKithJRCE7yisrq%2Flg6DjROeAC0OU7Gph7iBN40cgjQpAQA3sKgvaBBNABKkJB4AMrxiQBcTDjQNAA0PX0DAEK4zTjr7jN4c4vLvQMAwvo4ALKQzdK7%2B0t9%2FU6nUpfX5zTeqAgAivM4XLd5vcVk9pNIAGoIHBfGLlQEHB5lOSoHaqFTA3oAOmxNQRfT0UhuoG6Dwe2MxuMxBIMGNJDgwUIBkgMFNI8wA2ioAKwABh5KgAurSHk49D5GTNqTJMehUEg8JyAGx8wXCvoMTySs7STEhHAILicgAcKqFh1JOTgAGs9TAfDMVABiOQu9Hmh7oaAMbxawm6%2FWGlQAJlNtIAvrSpa84cT3X1vFCrTMSaTUxq8A7na61anLTbFNB7czpXqDcbQ3HehHzdWwyYgA)? Is the example that I have used in the screenshot of my previous comment, and it works in all cases (light/dark/auto).

**Comment by martindufort** [comment]
Ok let me make further tests to validate that everything in my side is ok. Thanks for timely reply.

**Comment by martindufort** [comment]
I fired up the Web Inspector and it states that the CSS variables for the dark mode are unused....
So I'm sure I did something wrong somewhere..

<img width="303" alt="CleanShot 2024-02-14 at 18 42 27@2x" src="https://github.com/jmjuanes/siimple/assets/28934641/7da5a3ae-cf1a-4703-ada2-c914439d4a3e">

**Comment by martindufort** [comment]
OK after further investigation, I found the issue which is not related to `siimple`. 

FYI: I'm using 11TY to generate the resulting static site and in some cases the update `css` was not copied to the distribution directory. 

Sorry for the noise and thanks for your support. 
Love this CSS toolkit...
