### ISSUE TITLE
No Keyboard Support

### ISSUE THREAD

**Issue by troxler** [jmjuanes/siimple#67]
**Describe the bug**
Some form components are not usable with the keyboard. Buttons, checkboxes, radio buttons, and switches are not focussable using the keyboard's tab key and there is thus no way to interact with them. This might also affect screen readers.

**To Reproduce**
1. Open the demo page
2. Try to select any of those elements by hitting you tab key

**Expected behavior**
Form elements must be focussable with the keyboard and they must allow interaction from the keyboard.

**Desktop (please complete the following information):**
* OS: macOS 10.13.6
* Browser: Firefox 
* Version 66.0.3

**Comment by jmjuanes** [comment]
Hello @troxler . Sorry, but I was unable to find a solution to make the radio, checkbox and switch elements focussable, because these elements hide the input element that are attached to :(

**Comment by troxler** [comment]
Luckily, it is possible to make any element focusable with the `tabindex` attribute. See [Indicating focus to improve accessibility](https://hacks.mozilla.org/2019/06/indicating-focus-to-improve-accessibility/) (especially the section about "Special cases") and [`tabindex` on MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex) for details.
