### ISSUE TITLE
Add sticky option to navbar

### ISSUE THREAD

**Issue by kiwioverseas** [jmjuanes/siimple#73]
Add an option to the navbar to make it stick to top when scrolling.

**Comment by jmjuanes** [comment]
`v4.0.0` will support navbar fixed to top or fixed to bottom.

![image](https://user-images.githubusercontent.com/5751201/71544290-b7d40e00-297d-11ea-9d81-85238d732785.png)

**Comment by offradar** [comment]
> `v4.0.0` will support navbar fixed to top or fixed to bottom.

Thanks! Does v4 have a release date?

**Comment by jmjuanes** [comment]
> Thanks! Does v4 have a release date?

Not a fixed date, but I hope that at the end of this month it will be published.
