### ISSUE TITLE
Responsive navbar

### ISSUE THREAD

**Issue by willfinnigan** [jmjuanes/siimple#75]
Hi,

Sorry if this is already covered somehow, but is there an easy way to make a responsive navbar?

Maybe this could be included as an example?

**Comment by jmjuanes** [comment]
Hello @willfinnigan (sorry for the delay to answer your question).

> Sorry if this is already covered somehow, but is there an easy way to make a responsive navbar?

The responsive navbar is something that we have in mind to improve for the `v4.0.0`. At this moment, You can use the sizes of the `siimple-navbar` element to make the navbar responsive (https://docs.siimple.xyz/layout/navbar.html and https://docs.siimple.xyz/layout/overview.html). 

> Maybe this could be included as an example?

Yes, or maybe as a tutorial.

**Comment by jmjuanes** [comment]
`v4.0.0` will support responsive navbar using only CSS (no Javascript or extra HTML elements are required)  :tada:

![image](https://user-images.githubusercontent.com/5751201/71544109-485d1f00-297b-11ea-8601-2014ffc98193.png)

![image](https://user-images.githubusercontent.com/5751201/71544131-78a4bd80-297b-11ea-83f4-de3aab2b3ea3.png)
